
tool.hovermodule.1=Администрира левитиращи модули
tool.hovermodule.left=Създава/Променя левитиращ модул
tool.hovermodule.right=Копира настройки/Въвежда напред
tool.hovermodule.right_use=Копира настройки/Въвежда нагоре
tool.hovermodule.reload=Трие левитиращ модул
tool.hovermodule.name=Инструмент за левитращи модули
tool.hovermodule.desc=Менижира левитиращи модули
tool.hovermodule.0=Ляво копче да създадете/конвертирате/промените, дясно да вземете настройките, презаредете за да премахнете
Cleanup_hovermodules=Левитиращи модули
Cleaned_hovermodules=Левитиращите модули са почистени
SBoxLimit_hovermodules=Достигнахте границата на създадените левитиращи модули!
