
tool.hovermodule.1=Administrates hover modules
tool.hovermodule.left=Create/update hover module
tool.hovermodule.right=Copy settings/Apply forward
tool.hovermodule.right_use=Copy settings/Apply up
tool.hovermodule.reload=Remove hover module
tool.hovermodule.name=Hover module tool
tool.hovermodule.desc=Administrates hover modules
tool.hovermodule.0=Left Click to spawn/convert/update, right click to get settings, reload to remove
tool.hovermodule.uname_con=Name\:
tool.hovermodule.uname_tip=Here goes the name of your hover module
tool.hovermodule.uploc_con=Up local\:
tool.hovermodule.uploc_tip=Up direction of the custom coordinate system
tool.hovermodule.fwloc_con=Forward local\:
tool.hovermodule.fwloc_tip=Forward direction of the custom coordinate system
tool.hovermodule.cnloc_con=Center offset\:
tool.hovermodule.cnloc_tip=The center offset vector relative to the new coordinates
tool.hovermodule.mass_con=Module mass\:
tool.hovermodule.mass_tip=Defines how heavy the hover module will be
tool.hovermodule.enmassp_con=Enable mass protection
tool.hovermodule.enmassp_tip=Check this to enable hover module mass protection
tool.hovermodule.numfor_con=Numpad force\:
tool.hovermodule.numfor_tip=How much force is applied when entity is driven via numpad
tool.hovermodule.tick_con=Sampling time [ms]\:
tool.hovermodule.tick_tip=This adjusts the hover module sampling time in [ms]
tool.hovermodule.descr_def=Select hover mode...
tool.hovermodule.descr_tip=This contains hover module definitions. For custom mode select
tool.hovermodule.keyon_con=Key power on (toggled)\:
tool.hovermodule.keyf_con=Key forward\:
tool.hovermodule.keyr_con=Key reverse\:
tool.hovermodule.fileovr_con=Enable file data override
tool.hovermodule.fileovr_tip=Click this if you prefer to use panel over the file settings
tool.hovermodule.modovr_con=Enable model override
tool.hovermodule.modovr_tip=Click this if you want to use different prop for a predefined unit
tool.hovermodule.centmc_con=Enable center from mass-center
tool.hovermodule.centmc_tip=Click this if you prefer using the mass-center instead of a custom center
tool.hovermodule.numtog_con=Enable toggle throttle
tool.hovermodule.numtog_tip=Check this to use toggled numpad throttle
tool.hovermodule.ushitgl_con=Enable global trace targets
tool.hovermodule.ushitgl_tip=Check this to use the global trace targets if none are provided
tool.hovermodule.drwucs_con=Coordinate system scale
tool.hovermodule.drwucs_tip=Adjust this until you get comfortable with coordinate system drawn size
tool.hovermodule.drwinfo_con=Draw balloon info
tool.hovermodule.drwinfo_tip=Check this to enable information balloon drawing
tool.hovermodule.drwhalo_con=Draw entity halo
tool.hovermodule.drwhalo_tip=Check this to enable entity halo drawing
tool.hovermodule.sendobj_con=Draw sensor parameters
tool.hovermodule.sendobj_tip=Check this to enable sensor parameters drawing
tool.hovermodule.sendnam_con=Draw sensor names
tool.hovermodule.sendnam_tip=Check this to enable sensor names drawing
tool.hovermodule.frcdobj_con=Draw forcer parameters
tool.hovermodule.frcdobj_tip=Check this to enable forcers drawing
tool.hovermodule.frcdnam_con=Draw forcer names
tool.hovermodule.frcdnam_tip=Check this to enable forcer names drawing
tool.hovermodule.forcedp_con=Force depth\:
tool.hovermodule.forcedp_tip=Adjust throttle force up local position
tool.hovermodule.encfdp_con=Enable contraption force depth
tool.hovermodule.encfdp_tip=Check this to enable initializing foce depth from contraption total mass center
tool.hovermodule.drwfrd_con=Draw force depth
tool.hovermodule.drwfrd_tip=Check this to enable drawing the throttle force offset
tool.hovermodule.menu_name=Hover module configuration
tool.hovermodule.comb_dir=Select a folder to browse. This will change the file browser base directory loading files from different locations. Update the convar /hovermodule_dirlist/ to change the directory list
Cleanup_hovermodules=Hover modules
Cleaned_hovermodules=Cleaned up hover modules
SBoxLimit_hovermodules=You have hit the hover modules limit!
